version: '3.0'

services:
  webapp:
    image: node:latest
    container_name: webapp_19127368
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    command: >
      sh -c " 
        cd /app &&
        npm install &&
        HOST=0.0.0.0 npm start &&
        tail -f /dev/null
      "
  server:
    image: python:latest
    container_name: server_19127368
    volumes:
      - ./backend:/app
    ports:
      - 80:80
    command: >
      sh -c "
        cd /app &&
        python -m venv .venv
        . .venv/bin/activate &&
        pip install --upgrade pip &&
        pip install -r requirements.txt &&
        cd server &&
        python manage.py makemigrations && 
        python manage.py migrate && 
        python manage.py runserver 0.0.0.0:80 &&
        tail -f /dev/null
      "
    depends_on:
      db:
        condition: service_healthy

    restart: always
  db:
    image: mysql:latest
    container_name: db-mysql
    volumes:
      - ./.db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_HOST=%
      - MYSQL_HOST=localhost

    healthcheck:
      test: mysqladmin ping
      timeout: 20s
      retries: 10

    restart: always