# Generated by Django 4.1.3 on 2022-11-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_group_end_date_remove_group_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='invite_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
