# Generated by Django 4.1.3 on 2022-12-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_member_invite_code_member_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateTimeField(null=True),
        ),
    ]
